// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volar.Data;

#nullable disable

namespace Volar.Data.Migrations
{
    [DbContext(typeof(VolarDbContext))]
    partial class VolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Volar.Data.Entities.CompletionEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimateSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentIdSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("ParentIdSnapshot");

                    b.HasIndex("TaskId");

                    b.ToTable("CompletionEvents");
                });

            modelBuilder.Entity("Volar.Data.Entities.ConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ExternalSatisfied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TaskDoneTargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Volar.Data.Entities.ParseCorrectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ParseCorrections");
                });

            modelBuilder.Entity("Volar.Data.Entities.ReminderRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FireAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHighUrgency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OffsetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("scheduled");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FireAt");

                    b.HasIndex("TaskId");

                    b.ToTable("ReminderRecords");
                });

            modelBuilder.Entity("Volar.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("DelegationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Frog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("KindRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("task");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityRaw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecurrenceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderOverrideJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTranscript")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("todo");

                    b.Property<int>("SwitchAwayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhenRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("now");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ParentId");

                    b.HasIndex("StatusRaw");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Volar.Data.Entities.ConditionEntity", b =>
                {
                    b.HasOne("Volar.Data.Entities.TaskEntity", null)
                        .WithMany("Conditions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Volar.Data.Entities.ReminderRecordEntity", b =>
                {
                    b.HasOne("Volar.Data.Entities.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Volar.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("Volar.Data.Entities.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Volar.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
